### PR TITLE
Lesson 2

### PR DESCRIPTION
**Pull request by piki**
See lesson-plan.md for what we're doing this week.  In a nutshell:
- Programming concepts: text painting, variables, game state, `if` conditionals
- Game features: title text, "paused" text, keeping score
- Optional game features, time permitting: high scores (only until reloaded), coins

See the [lesson-2-solved branch](https://github.com/piki/patandpat.js/tree/lesson-2-solved) for the solutions.

### CODE REVIEW

**Comment by PlaidShirtPat** [comment]
Looks good, just a few questions/comments.

For each lesson, do we want to start off each class with a quick review quiz as the "what did we learn?" part?

Besides increment (++) are we going to cover any other kinds of arithmetic? 

Should we start with `score = score + 1` and then introduce the increment operator as a short cut to make what is actually happening a bit more obvious?

**Comment by piki** [comment]
Definitely want to do a review quiz.  Alia used Kahoots for the Scratch class, and the kids loved it, so I figured I'd go with that.

Now that you ask, we could also teach them `canvas.height/2` for centering text.  That's actually how the text was laid out before, and I changed it to ugly, hard-coded coordinates because they're more explainable than `measureText` and dimensions variables.  But we could reintroduce `canvas.height/2` because that's pretty easy.

I'm even tempted to introduce `canvas.width/2` to :trollface: them and have them explain why it's wrong.

I'll introduce `++`, not because it's particularly important, but because it's something they're likely to see if they start reading anyone else's JavaScript code.

**Comment by piki** [comment]
New commit :point_up: with `SCORE++` and `canvas.height / 2` in the Keynote and PDF.

**Comment by PlaidShirtPat** [comment]
I agree that knowing `++` is important. I suggesting we show the progression from `thing = thing +1` >> `thing += 1` >> `thing++` just to give a more complete view of the syntax.

I may look into making a reference sheet for various operators and constructs (if, while, arithmetic ops, common functions).

**Pull request merged**
